# Corrected and Scaled microservice-app.yaml

apiVersion: apps/v1
kind: Deployment
metadata:
  name: catalog
spec:
  replicas: 1 # Scaled to 2 replicas
  selector:
    matchLabels:
      run: catalog
  template:
    metadata:
      labels:
        run: catalog
    spec:
      containers:
      - image: docker.io/vidit12/microservice-kubernetes-demo-catalog:prometheus
        name: catalog
        ports:
        - containerPort: 8080
        resources:
          requests:
            cpu: "200m"
            memory: "512Mi"
          limits:
            cpu: "500m"
            memory: "1Gi"

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: customer
spec:
  replicas: 1 # Scaled to 2 replicas
  selector:
    matchLabels:
      run: customer
  template:
    metadata:
      labels:
        run: customer
    spec:
      containers:
      - image: docker.io/vidit12/microservice-kubernetes-demo-customer:prometheus
        name: customer
        ports:
        - containerPort: 8080
        resources:
          requests:
            cpu: "200m"
            memory: "512Mi"
          limits:
            cpu: "500m"
            memory: "1Gi"

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: order
spec:
  replicas: 1 # Scaled to 2 replicas
  selector:
    matchLabels:
      run: order
  template:
    metadata:
      labels:
        run: order
    spec:
      containers:
      - image: docker.io/vidit12/microservice-kubernetes-demo-order:prometheus
        name: order
        ports:
        - containerPort: 8080
        resources:
          requests:
            cpu: "200m"
            memory: "512Mi"
          limits:
            cpu: "500m"
            memory: "1Gi"
---

apiVersion: v1
kind: Service
metadata:
  name: catalog
  labels:
    run: catalog
  annotations:
    prometheus.io/scrape: "true"
    prometheus.io/port: "8080"
    prometheus.io/path: "/actuator/prometheus"
spec:
  ports:
  - port: 8080
    protocol: TCP
    targetPort: 8080
    name: http
  selector:
    run: catalog
  type: ClusterIP # CORRECTED: Changed from LoadBalancer

---

apiVersion: v1
kind: Service
metadata:
  name: customer
  labels:
    run: customer
  annotations:
    prometheus.io/scrape: "true"
    prometheus.io/port: "8080"
    prometheus.io/path: "/actuator/prometheus"
spec:
  ports:
  - port: 8080
    protocol: TCP
    targetPort: 8080
    name: http
  selector:
    run: customer
  type: ClusterIP # CORRECTED: Changed from LoadBalancer

---

apiVersion: v1
kind: Service
metadata:
  name: order
  labels:
    run: order
  annotations:
    prometheus.io/scrape: "true"
    prometheus.io/port: "8080"
    prometheus.io/path: "/actuator/prometheus"
spec:
  ports:
  - port: 8080
    protocol: TCP
    targetPort: 8080
    name: http
  selector:
    run: order
  type: ClusterIP # CORRECTED: Changed from LoadBalancer