---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-prometheus-exporter
  labels:
    app: nginx-prometheus-exporter
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx-prometheus-exporter
  template:
    metadata:
      labels:
        app: nginx-prometheus-exporter
    spec:
      containers:
      - name: nginx-prometheus-exporter
        image: nginx/nginx-prometheus-exporter:0.11.0
        args:
          - -nginx.scrape-uri=http://nginx-loadbalancer-service:8081/nginx_status
        ports:
        - name: metrics
          containerPort: 9113
        resources:
          requests:
            cpu: 50m
            memory: 64Mi
          limits:
            cpu: 100m
            memory: 128Mi
---
apiVersion: v1
kind: Service
metadata:
  name: nginx-prometheus-exporter
  labels:
    app: nginx-prometheus-exporter
  annotations:
    prometheus.io/scrape: "true"
    prometheus.io/port: "9113"
spec:
  type: ClusterIP
  ports:
  - port: 9113
    targetPort: 9113
    protocol: TCP
    name: metrics
  selector:
    app: nginx-prometheus-exporter
